server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://mysql-server:3306/coin-exchange?useSSL=false&serverTimezon=GMT%28&allowPublicKeyRetrieval=true
    username: root
    password: 2539417782@Qq
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: redis-server
#    port: 6379
#    password: 123456